# Generated by Django 5.1.2 on 2024-11-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt_agent", "0002_conversationhistory_thread_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationhistory",
            name="assistant_id",
        ),
    ]
