# Generated by Django 5.1.3 on 2024-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatgpt_agent", "0003_remove_conversationhistory_assistant_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversationhistory",
            index=models.Index(
                fields=["timestamp"], name="chatgpt_age_timesta_3b11bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationhistory",
            index=models.Index(
                fields=["thread_id"], name="chatgpt_age_thread__2c55b4_idx"
            ),
        ),
    ]
