# Generated by Django 5.1.3 on 2024-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_question_video_test"),
        ("video", "0003_video_topic"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["correct_option"], name="quiz_answer_correct_210c93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["text"], name="quiz_questi_text_bfd841_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["video"], name="quiz_test_video_i_0e6ff4_idx"),
        ),
    ]
